import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/shared/navbar';
import { ThemeProvider } from '@/components/providers/theme';
import AuthProvider from '@/components/providers/auth.provider';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
					<Toaster position='top-center' />
					<Navbar />
					<AuthProvider>
						<div>{children}</div>
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
